name: Test CodeX Java

on:
  workflow_call:
    inputs:
      team-name:
        required: true
        type: string
      pr_head_sha:
        required: true
        type: string
      machine_name:
        required: true
        type: string
    secrets:
      test-repo:
        required: true
      auth-token:
        required: true
      backend-url:
        required: true
      auth-key:
        required: true

jobs:
  test-bug-01:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 01
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=JwtServiceTest#BUG002 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-002"
            }'
          fi
          exit ${result}

  test-bug-02:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 02
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=JwtServiceTest#BUG003 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-003"
            }'
          fi
          exit ${result}

  test-bug-03:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 03
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=JwtServiceTest#BUG004 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-004"
            }'
          fi
          exit ${result}

  test-bug-04:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 04
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=JwtServiceTest#BUG005 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-005"
            }'
          fi
          exit ${result}

  test-bug-05:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 05
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=JwtServiceTest#BUG006 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-006"
            }'
          fi
          exit ${result}

  test-bug-06:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 06
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=JwtServiceTest#BUG007 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-007"
            }'
          fi
          exit ${result}

  test-bug-07:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 07
        shell: bash {0}
        run: |
          set +e
          # Note: Original had mvn test BUG009 but curl BUG-008
          mvn -Dtest=JwtServiceTest#BUG009 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-008"
            }'
          fi
          exit ${result}

  test-bug-08:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 08
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=JwtServiceTest#BUG009 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-009"
            }'
          fi
          exit ${result}

  test-bug-09:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 09
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=AuthServiceTest#BUG010 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-010"
            }'
          fi
          exit ${result}

  test-bug-10:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 10
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=AuthServiceTest#BUG011 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-011"
            }'
          fi
          exit ${result}

  test-bug-11:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 11
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=AuthServiceTest#BUG012 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-012"
            }'
          fi
          exit ${result}

  test-bug-12:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 12
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=UserServiceTest#BUG013 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-013"
            }'
          fi
          exit ${result}

  test-bug-13:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 13
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=UserServiceTest#BUG014 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-014"
            }'
          fi
          exit ${result}

  test-bug-14:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 14
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=UserServiceTest#BUG015 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-015"
            }'
          fi
          exit ${result}

  test-bug-15:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 15
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=UserServiceTest#BUG016 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-016"
            }'
          fi
          exit ${result}

  test-bug-16:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 16
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=UserServiceTest#BUG017 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-017"
            }'
          fi
          exit ${result}

  test-bug-17:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 17
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=UserServiceTest#BUG018 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-018"
            }'
          fi
          exit ${result}

  test-bug-18:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 18
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=AdminServiceTest#BUG019 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-019"
            }'
          fi
          exit ${result}

  test-bug-19:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 19
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=AdminServiceTest#BUG020 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-020"
            }'
          fi
          exit ${result}

  test-bug-20:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 20
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=AdminServiceTest#BUG021 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-021"
            }'
          fi
          exit ${result}

  test-bug-21:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 21
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=AdminServiceTest#BUG022 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-022"
            }'
          fi
          exit ${result}

  test-bug-22:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 22
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=AdminServiceTest#BUG023 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-023"
            }'
          fi
          exit ${result}

  test-bug-23:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 23
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=AdminServiceTest#BUG024 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-024"
            }'
          fi
          exit ${result}

  test-bug-24:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 24
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=OAuthServiceTest#BUG025 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-025"
            }'
          fi
          exit ${result}

  test-bug-25:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 25
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=OAuthServiceTest#BUG026 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-026"
            }'
          fi
          exit ${result}

  test-bug-26:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 26
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=OAuthServiceTest#BUG027 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-027"
            }'
          fi
          exit ${result}

  test-bug-27:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 27
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=OAuthServiceTest#BUG028 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-028"
            }'
          fi
          exit ${result}

  test-bug-28:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 28
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=OAuthServiceTest#BUG029 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-029"
            }'
          fi
          exit ${result}

  test-bug-29:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 29
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=EmailUtilTest#BUG030 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-030"
            }'
          fi
          exit ${result}

  test-bug-30:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 30
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=EmailUtilTest#BUG031 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-031"
            }'
          fi
          exit ${result}

  test-bug-31:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 31
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=SecurityConfigurationTest#BUG032 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-032"
            }'
          fi
          exit ${result}

  test-bug-32:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 32
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=SecurityConfigurationTest#BUG033 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-033"
            }'
          fi
          exit ${result}

  test-bug-33:
    runs-on: ${{ inputs.machine_name }}
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr_head_sha }}

      - name: checkout tests
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.test-repo }}
          token: ${{ secrets.auth-token }}
          sparse-checkout: java
          sparse-checkout-cone-mode: false
          path: tests

      - name: setup test files
        run: |
          mkdir -p src/test/java/com/codejam/codex/authzen
          mv tests/* src/test/java/com/codejam/codex/authzen/

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: run test on bug 33
        shell: bash {0}
        run: |
          set +e
          mvn -Dtest=SecurityConfigurationTest#BUG034 test > /dev/null 2>&1
          result=$?
          if [ ${result} -ne 0 ]; then
              echo "FAILED"
          else
            echo "PASSED"
            curl -X POST ${{ secrets.backend-url }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-token: ${{ secrets.auth-key }}" \
            -d '{
                "tablePrefix":"uni_",
                "teamName": "${{ inputs.team-name }}",
                "bugCode": "BUG-034"
            }'
          fi
          exit ${result}